### ISSUE TITLE
Can't check the weather from inside a building

### ISSUE THREAD

**Issue by Guigui220D** [Random-People/Chit-chat#3]
I get a "sky not visible" error when trying to check for the weather. Only happens when under a roof, inside a building or in a vehicle.

**Comment by ghost** [comment]
It seems that the window isn't transparent. Opened issue https://github.com/Random-People/Chit-chat/issues/4

**Comment by Guigui220D** [comment]
Window was transparent, I was looking at the wall, sorry for the inconvinience
