### ISSUE TITLE
Window isn't transparent

### ISSUE THREAD

**Issue by ghost** [Random-People/Chit-chat#4]
I get a "sky not visible" error when trying to check for the weather. Only happens when looking out the window.

**Comment by Guigui220D** [comment]
Windows should be transparent to visible light if made of proper glass, what electromagnetic frequency are you using to see?

**Comment by ghost** [comment]
With a transparent window, how can you not check the weather? You can see everything outside.

**Comment by Guigui220D** [comment]
Seems like what I was looking at was a wall and not a window

**Comment by jeanthom** [comment]
Have you tried running non-GNU/LInux instead of Windows?

**Comment by ghost** [comment]
@jeanthom You know, Windows can have transparent windows! E.g.
![Capture](https://user-images.githubusercontent.com/43641740/87876942-dc70ff80-ca0d-11ea-8efb-1c3192c9855b.PNG)

**Comment by Guigui220D** [comment]
But the problem was with walls, any way on unix systems to see through walls? I don't think it's possible on Windows at all, Windows only likes windows. This could be very useful for checking weather on window-less non windows houses.

**Comment by Guigui220D** [comment]
Maybe we should compile with -Wall instead of -Window?

**Comment by jeanthom** [comment]
Maybe it's a hardware issue?
