### ISSUE TITLE
Sky Only Partially Visible Through Window

### ISSUE THREAD

**Issue by lyxal** [Random-People/Chit-chat#5]
I'm expecting that I can see the full sky when there is only half the sky visible.

**Comment by lyxal** [comment]
FWIW, window seems fully operational, BLINDos is installed and seems to be running.

**Comment by Guigui220D** [comment]
Is there a data structure such as a tree that could be preventing you from accessing the entirety of the sky?

**Comment by lyxal** [comment]
> Is there a data structure such as a tree that could be preventing you from accessing the entirety of the sky?

No, it's a fresh install, with no data at all

**Comment by Guigui220D** [comment]
If you're talking about the ground blocking half the sky, it's a known issue and a won't fix, you'll have to wait 12 hours to be able to look at other parts of the sky

**Comment by lyxal** [comment]
But from the half I can see, it's day time.

**Comment by lyxal** [comment]
Never mind, it turns out BLINDos was down, blocking half the sky.
